language: python
arch:
    - ppc64le
    - amd64
python:
    - "3.6"

addons:
    apt:
        sources:
            - trusty-media
        packages:
            - ffmpeg

install:
    - python setup.py install

script:
    - pytest
