language: python

python:
    - "2.7"
    - "3.6"

addons:
    apt:
        sources:
            - trusty-media
        packages:
            - ffmpeg

install:
    - python setup.py install

script:
    - pytest
